let content=null;
const $=id=>document.getElementById(id); const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"})[c]);
function status(msg,type=""){const e=$("status");e.textContent=msg;e.className=`status ${type}`}
function get(obj,path){return path.split(".").reduce((o,k)=>o?.[k],obj)}
function set(obj,path,val){const ks=path.split(".");let o=obj;ks.slice(0,-1).forEach(k=>o=o[k]??=( {} ));o[ks.at(-1)]=val}
const copyFields=["companyName","shortName","location","heroBadge","heroTitle","heroSubtitle","aboutTitle","aboutText1","aboutText2"];
async function load(){status("جاري التحميل...");try{const r=await fetch(`content.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error("تعذر تحميل content.json");content=await r.json();hydrate();status("تم تحميل المحتوى","ok")}catch(e){status(e.message,"bad")}}
function hydrate(){
  $("brandLogo").value=content.brand?.logo||"";$("brandPrimary").value=content.brand?.primary||"#071827";$("brandAccent").value=content.brand?.accent||"#f4b73f";$("brandAccent2").value=content.brand?.accent2||"#df7d2d";showLogo();
  $("mediaHero").value=content.media?.hero||"";$("mediaAboutMain").value=content.media?.aboutMain||"";$("mediaAboutSide").value=content.media?.aboutSide||"";
  ["ar","en"].forEach(lang=>copyFields.forEach(key=>{const e=$(`${lang}_${key}`);if(e)e.value=get(content,`copy.${lang}.${key}`)||""}));
  renderServices();renderProjects();renderPhones();renderEmails();
}
function showLogo(){const src=$("brandLogo").value.trim(),p=$("logoPreview");if(src){p.src=src;p.style.display="block"}else p.style.display="none"}
function renderServices(){$("servicesEditor").innerHTML=(content.services||[]).map((s,i)=>`<div class="row-card" data-service="${i}"><div class="row-head"><strong>خدمة ${i+1}</strong><button type="button" class="remove" onclick="removeService(${i})">حذف</button></div><div class="grid"><div><label>العنوان عربي</label><input data-ar-title value="${esc(s.ar?.title)}"></div><div><label>English title</label><input data-en-title dir="ltr" value="${esc(s.en?.title)}"></div><div class="full"><label>الوصف العربي</label><textarea data-ar-desc>${esc(s.ar?.description)}</textarea></div><div class="full"><label>English description</label><textarea data-en-desc dir="ltr">${esc(s.en?.description)}</textarea></div><div><label>Icon key</label><input data-icon value="${esc(s.icon||"boxes")}"><div class="hint">bolt / boxes / build / tender / trade / support</div></div></div></div>`).join("")}
function renderProjects(){$("projectsEditor").innerHTML=(content.projects||[]).map((p,i)=>`<div class="row-card" data-project="${i}"><div class="row-head"><strong>عنصر ${i+1}</strong><button type="button" class="remove" onclick="removeProject(${i})">حذف</button></div><div class="grid"><div><label>التصنيف عربي</label><input data-ar-cat value="${esc(p.ar?.category)}"></div><div><label>English category</label><input data-en-cat dir="ltr" value="${esc(p.en?.category)}"></div><div><label>العنوان عربي</label><input data-ar-title value="${esc(p.ar?.title)}"></div><div><label>English title</label><input data-en-title dir="ltr" value="${esc(p.en?.title)}"></div><div class="full"><label>الوصف العربي</label><textarea data-ar-desc>${esc(p.ar?.description)}</textarea></div><div class="full"><label>English description</label><textarea data-en-desc dir="ltr">${esc(p.en?.description)}</textarea></div><div class="full"><label>رابط / مسار الصورة</label><input data-image value="${esc(p.image||"")}"></div><div class="full"><label>رفع صورة جديدة</label><input data-image-file type="file" accept="image/png,image/jpeg,image/webp"></div></div></div>`).join("")}
function renderPhones(){$("phonesEditor").innerHTML=(content.contact?.phones||[]).map((p,i)=>`<div class="row-card" data-phone="${i}"><div class="row-head"><strong>رقم ${i+1}</strong><button type="button" class="remove" onclick="removePhone(${i})">حذف</button></div><div class="grid"><div><label>وصف عربي</label><input data-ar-label value="${esc(p.labelAr)}"></div><div><label>English label</label><input data-en-label dir="ltr" value="${esc(p.labelEn)}"></div><div><label>الرقم الظاهر</label><input data-number dir="ltr" value="${esc(p.number)}"></div><div><label>WhatsApp digits</label><input data-wa dir="ltr" value="${esc(p.whatsapp)}"><div class="hint">مثال للرقم 01093029731: اكتب 201093029731 بدون + وبدون صفر البداية.</div></div></div></div>`).join("")}
function renderEmails(){$("emailsEditor").innerHTML=(content.contact?.emails||[]).map((e,i)=>`<div class="row-card" data-email="${i}"><div class="row-head"><strong>إيميل ${i+1}</strong><button type="button" class="remove" onclick="removeEmail(${i})">حذف</button></div><input type="email" dir="ltr" value="${esc(e)}"></div>`).join("")}
function collectRepeaters(){
  content.services=[...document.querySelectorAll("[data-service]")].map(r=>({icon:r.querySelector("[data-icon]").value.trim()||"boxes",ar:{title:r.querySelector("[data-ar-title]").value.trim(),description:r.querySelector("[data-ar-desc]").value.trim()},en:{title:r.querySelector("[data-en-title]").value.trim(),description:r.querySelector("[data-en-desc]").value.trim()}}));
  content.projects=[...document.querySelectorAll("[data-project]")].map(r=>({image:r.querySelector("[data-image]").value.trim(),ar:{category:r.querySelector("[data-ar-cat]").value.trim(),title:r.querySelector("[data-ar-title]").value.trim(),description:r.querySelector("[data-ar-desc]").value.trim()},en:{category:r.querySelector("[data-en-cat]").value.trim(),title:r.querySelector("[data-en-title]").value.trim(),description:r.querySelector("[data-en-desc]").value.trim()}}));
  content.contact??={};content.contact.phones=[...document.querySelectorAll("[data-phone]")].map(r=>({labelAr:r.querySelector("[data-ar-label]").value.trim(),labelEn:r.querySelector("[data-en-label]").value.trim(),number:r.querySelector("[data-number]").value.trim(),whatsapp:r.querySelector("[data-wa]").value.replace(/\D/g,"")}));content.contact.emails=[...document.querySelectorAll("[data-email] input")].map(e=>e.value.trim()).filter(Boolean);
}
function collect(){collectRepeaters();content.brand??={};content.brand.logo=$("brandLogo").value.trim();content.brand.primary=$("brandPrimary").value;content.brand.accent=$("brandAccent").value;content.brand.accent2=$("brandAccent2").value;content.media??={};content.media.hero=$("mediaHero").value.trim();content.media.aboutMain=$("mediaAboutMain").value.trim();content.media.aboutSide=$("mediaAboutSide").value.trim();["ar","en"].forEach(lang=>copyFields.forEach(key=>{const e=$(`${lang}_${key}`);if(e)set(content,`copy.${lang}.${key}`,e.value.trim())}));return content}
window.removeService=i=>{collectRepeaters();content.services.splice(i,1);renderServices()};window.removeProject=i=>{collectRepeaters();content.projects.splice(i,1);renderProjects()};window.removePhone=i=>{collectRepeaters();content.contact.phones.splice(i,1);renderPhones()};window.removeEmail=i=>{collectRepeaters();content.contact.emails.splice(i,1);renderEmails()};
$("addService").onclick=()=>{collectRepeaters();content.services.push({icon:"boxes",ar:{title:"خدمة جديدة",description:""},en:{title:"New service",description:""}});renderServices()};$("addProject").onclick=()=>{collectRepeaters();content.projects.push({image:"",ar:{category:"",title:"عنصر جديد",description:""},en:{category:"",title:"New capability",description:""}});renderProjects()};$("addPhone").onclick=()=>{collectRepeaters();content.contact.phones.push({labelAr:"الهاتف / واتساب",labelEn:"Phone / WhatsApp",number:"",whatsapp:""});renderPhones()};$("addEmail").onclick=()=>{collectRepeaters();content.contact.emails.push("");renderEmails()};$("brandLogo").oninput=showLogo;
function utf8b64(str){const bytes=new TextEncoder().encode(str);let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}async function fileb64(file){const bytes=new Uint8Array(await file.arrayBuffer());let bin="";for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(bin)}
async function gh(url,token,opt={}){const r=await fetch(url,{...opt,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(opt.headers||{})}});if(!r.ok){let d="";try{d=(await r.json()).message||""}catch{}throw new Error(`GitHub API: ${r.status} ${d}`)}return r.json()}
function safeName(name="image.jpg"){const parts=name.split(".");const ext=(parts.length>1?"."+parts.pop():".jpg").toLowerCase().replace(/[^.a-z0-9]/g,"");const base=parts.join(".").toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/^-|-$/g,"")||"asset";return `${base}-${Date.now()}${ext}`}
async function uploadFile(owner,repo,branch,token,file,pathPrefix){const name=safeName(file.name),path=`${pathPrefix}/${name}`,api=`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path.split("/").map(encodeURIComponent).join("/")}`;await gh(api,token,{method:"PUT",body:JSON.stringify({message:`Upload ${name}`,content:await fileb64(file),branch})});return path}
async function uploadAssets(owner,repo,branch,token){const logo=$("logoFile").files?.[0];if(logo){status("جاري رفع اللوجو...");const path=await uploadFile(owner,repo,branch,token,logo,"assets/brand");$("brandLogo").value=path;content.brand.logo=path}
  const mediaUploads=[["heroFile","mediaHero","Hero"],["aboutMainFile","mediaAboutMain","About main"],["aboutSideFile","mediaAboutSide","About side"]];
  for(const [fileId,inputId,label] of mediaUploads){const file=$(fileId).files?.[0];if(!file)continue;status(`جاري رفع صورة ${label}...`);const path=await uploadFile(owner,repo,branch,token,file,"assets/media");$(inputId).value=path;}
  const rows=[...document.querySelectorAll("[data-project]")];for(let i=0;i<rows.length;i++){const f=rows[i].querySelector("[data-image-file]")?.files?.[0];if(!f)continue;status(`جاري رفع صورة ${i+1}...`);const path=await uploadFile(owner,repo,branch,token,f,"assets/projects");rows[i].querySelector("[data-image]").value=path}}
async function publish(){const owner=$("ghOwner").value.trim(),repo=$("ghRepo").value.trim(),branch=$("ghBranch").value.trim()||"main",token=$("ghToken").value.trim();if(!owner||!repo||!token){status("اكتب Owner وRepository وToken أولًا","bad");return}localStorage.setItem("alnogoom-gh-owner",owner);localStorage.setItem("alnogoom-gh-repo",repo);localStorage.setItem("alnogoom-gh-branch",branch);try{await uploadAssets(owner,repo,branch,token);const updated=collect();const api=`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/content.json`;status("جاري قراءة النسخة الحالية...");const ex=await gh(`${api}?ref=${encodeURIComponent(branch)}`,token);status("جاري النشر...");await gh(api,token,{method:"PUT",body:JSON.stringify({message:"Update bilingual website content",content:utf8b64(JSON.stringify(updated,null,2)+"\n"),sha:ex.sha,branch})});status("تم النشر بنجاح. GitHub Pages سيحدّث الموقع تلقائيًا.","ok")}catch(e){status(e.message,"bad")}}
$("reloadBtn").onclick=load;$("publishBtn").onclick=publish;$("ghOwner").value=localStorage.getItem("alnogoom-gh-owner")||"";$("ghRepo").value=localStorage.getItem("alnogoom-gh-repo")||"";$("ghBranch").value=localStorage.getItem("alnogoom-gh-branch")||"main";load();
